# Configuration file for sysmonitor.conf

# Various system accounts that we need to know about

gpscv account = cvgps

#ntp account = ntp-admin
ntp account = ntp-admin
ntp daemon = chronyd

# sysmonitor's log file
# log file = /usr/local/log/sysmonitor.log

# Current alarms are written to this directory
# so that other applications know about them 
alarm path = /usr/local/log/alarms/

# alerter delivers alarms to external targets (SMS, email, SNMP ...)
# This is where alarms are queued for delivery
# alerter queue = /usr/local/log/alert.log

# default threshold for raising alarms, in seconds
alarm threshold = 60


# The ntpd refclocks that we want to monitor
# Use a comma-separated list, with each item defining a section in this config file
ntpd refclocks = NMEA, REF, GPS

[NMEA]
refid = NMEA
name = NMEA

[REF]
refid = PPS0
name  = REF PPS

[GPS]
refid = PPS1
name  = RX PPS

# Added section Alarms on 2017-07-21 Louis Marais
# because lcdmonitor needs it...

[Alarms]

Status File Directory = /usr/local/log/alarms

