# Configuration file for Septentrio mosaicT

lstInternalFile,Identification
 
SetPPSparameters,sec1,Low2High,0,RxClock,60
SetTimeSyncSource,EventA
SetSignalTracking,+GPSL1PY+BDSB2A+GALE5

# Output NMEA sentences on Mosaic T COM2 (Pi5 based TTS)

# Turn on multiple sentences. ZDA gives UTC time data, and GGA & RMC is minimum required for gpsd to work properly
setNMEAOutput,Stream1,COM2,+ZDA+GGA+RMC,sec1
