#
[General]
NTP user = ntp-admin
# Specify which NTP daemon is in use. valid vales chrony,ntpd
NTP daemon = chronyd
# default location changed from local to global ELM 2018-09-13
sysmonitor config = /usr/local/etc/sysmonitor.conf

[UI]
Display mode = ntp
Show PRNs=1
LCD intensity=90
LCD contrast=95
LCD timeout=300

[GPSCV]
GPSCV user = cvgps
GPSCV config = /home/cvgps/etc/gpscv.conf
GPS restart command = su - cvgps -c 'kickstart.pl'
# Oscillators are LCXO,ULN1100,Furuno
Oscillator = Furuno

[OS]
Reboot command = /sbin/shutdown -r now
Poweroff command = /sbin/poweroff

[Network]
# Raspberry Pi+Ubuntu uses old-school interface names
LAN1 interface = eth0
# this optional
# LAN2 interface = eth1
# this is also optional
# USB  interface = usb0

# These are relevant only for non-Netplan viz RHEL
DNS = /etc/resolv.conf
Network = /etc/sysconfig/network
Eth0 = /etc/sysconfig/network-scripts/ifcfg-eth0


