# Configuration file for pi5ttsgpio.py

[main]
# A list of GPIOs to manage - these are free text fields
gpios = GPIO17, GPIO18, GPIO22, GPIO23, GPIO24, GPIO25, GPIO27

# The user for these GPIOs. This user will own the files for the GPIOs, and
# its home directory will be used as the root path for relative file links.
# It is assumed that the user running the script has the right to write to the
# configured user's home directory. The script is suppose to run as a service
# by the root user, so this should not be a problem.
user = cvgps

# Specify a lock file for the script
lock file = var/pi5ttsgpio.lock

# Optional log file - write GPIO changes to a log
log file = log/gpios.log

# Sample GPIO configuration
[GPIOx]
# A description of the function of the GPIO
description = This sample gpio signals when it is time for a coffee.
# The number of the GPIO in the BCM (GPIO) numbering scheme
gpio = 101
# Is this an input or an output?
io = OUTPUT
# Is this active high?  [1 | True | Yes] == True, [0 | False | No] == False
active high = 1
# The file name associated with this GPIO. This gan be the GPIO number of a
# descriptive name
file = gpios/gpiox.txt
# An optional initial value can be specified if the GPIO is an output, if
# it is not, the value written to the GPIO will be 'False', so 0 if the
# GPIO is active high, and 1 is the GPIO is active low.
# Accepted values are [0 | Low ] for a 0 output and [1 | High] for a 1 output
initial value = 0

[GPIO17]
description = GPSDO LOCK
gpio = 17
io = input
active high = true
file = gpios/GPSDO_LOCK.txt

[GPIO18]
description = GPSDO RESET
gpio = 18
io = Output
active high = yes
file = gpios/GPSDO_RESET.txt
initial value = 0

[GPIO22]
description = MOS T RESET
gpio = 22
io = output
active high = false
file = gpios/MOS_T_RESET.txt
initial value = 1

[GPIO23]
description = REF CLK SIG2 MON
gpio = 23
io = input
active high = 1
file = gpios/REF_CLK_SIG2_MON.txt

[GPIO24]
description = EX CLK SIG1 MON
gpio = 24
io = input
active high = Yes
file = gpios/EX_CLK_SIG1_MON.txt

[GPIO25]
description = GPSDO PWR ENABLE
gpio = 25
io = output
active high = true
file = gpios/GPSDO_PWR_ENABLE.txt
initial value = High

[GPIO27]
description = MOS T READY
gpio = 27
io = input
active high = yes
file = gpios/MOST_T_READY.txt
