PROGRAM = okbfloader
CXX = g++
INCLUDE = -I/usr/local/include
LDFLAGS= -L/usr/local/lib
LIBS= -lokFrontPanel -ldl 
DEFINES= -DOKFRONTPANEL
OBJECTS = BFLoader.o

.SUFFIXES: .o .cpp

all: $(PROGRAM)

$(OBJECTS): %.o:%.cpp
	$(CXX) $(INCLUDE) $(DEFINES) -c $<

$(PROGRAM): $(OBJECTS)
	$(CXX) $(LDFLAGS) -o $(PROGRAM) $(OBJECTS) $(LIBS)

install: $(PROGRAM)
	cp $(PROGRAM) /usr/local/sbin

clean:
	rm -f *.o $(PROGRAM)

