PROGRAM = okbfloader
CXX = g++
INCLUDE = -I../OpenOK2
LDFLAGS= 
LIBS= -lpthread -ldl -lusb-1.0
CXXFLAGS= -Wall 
DEFINES= -DDEBUG -DOPENOK2 
OBJECTS = BFLoader.o OpenOK.o
VPATH = ./:../OpenOK2

.SUFFIXES: .o .cpp

all: $(PROGRAM)

$(OBJECTS): %.o:%.cpp
	$(CXX) $(INCLUDE) $(DEFINES) -c $<

$(PROGRAM): $(OBJECTS)
	$(CXX) $(LDFLAGS) -o $(PROGRAM) $(OBJECTS) $(LIBS)

clean:
	rm -f *.o $(PROGRAM)

