PROGRAM = okcounterd
CXX = g++
INCLUDE = 
LDFLAGS= 
LIBS= -lpthread -ldl -lusb-1.0
CXXFLAGS= -Wall 
DEFINES= -DDEBUG -DOPENOK2
OBJECTS = OKCounterD.o Client.o Main.o Server.o OpenOK.o

.SUFFIXES: .o .cpp

all: $(PROGRAM)

$(OBJECTS): %.o:%.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDE) $(DEFINES) -c $<

$(PROGRAM): $(OBJECTS)
	$(CXX) $(LDFLAGS) -o $(PROGRAM) $(OBJECTS) $(LIBS)

clean:
	rm -f *.o $(PROGRAM)

