[Receiver]
# Script used for logging the receiver
# You need to specify the full path here
logging script = /home/cvgps/bin/plrxlog.py
gpscv user = cvgps

[Reference]
manufacturer = furuno
model = GF-8805 
# You need to specify the full path here
config file = /home/cvgps/etc/furuno.conf

[Paths]
# This will normally be under /usr/local
lock file = log/refmonitor.lock
