[main]


# Optional - default is /usr/local/bin/sbf2rin
# exec = /usr/local/bin/sbf2rin

[Receiver]

# Receiver data file format (jps/sbf)
file format = jps

# Receiver data file extension
# Note that these files are assumed to be named MJD.ext
file extension = jps

[RINEX]

# RINEX version, as per strings allowed by sbf2rin/jps2rin
version = 3.03 

# RINEX file name format (2 or 3)
name format = 2

# Directory for observation files
obs directory = RINEX

# Directory for navigation files
nav directory   = RINEX

# Station name for observation files
obs sta = AU09

# Station name for navigation files
# (for V3, mixed navigation files only at present)
nav sta = AU09

# GNSS to be excluded from RINEX, in the format used by  sbf2rin/jps2rin
exclusions = IWJ

# Create a navigation file
create nav file = yes


fix header = yes

# Header fixes are in the exact format of the line in the RINEX header
header fixes = etc/au09.header.txt

[Paths]

receiver data = raw

tmp = tmp
