# For Furuno GF-8805 

[main]
lock file = lockStatusCheck/furuno.lock

# The serial number is not software accessible. You have to place it in the 
# configuration if you want to access it from the system.
# The number can be found on the top of the GPSDO oscillator.

serial number = {Serial Number}

[comms]
port = /dev/furuno

# optional timeout (in seconds)
# Default is 10 seconds.

timeout = 30

[data]
path = raw/furuno
ext = gpsdo

[status]
path = lockStatusCheck
file name = furuno.status

# The following configuration options are optional
[receiver]
# This option can turn the antenna open warning on/off. This is useful when
# the antenna input is connected to a splitter without an impedance to simulate
# the presence of an antenna. Default is On.
# 0 == Off, 1 == On.

#antenna open warning = 0

# The default PPS pulse length is 500 ms. You can state the required pulse
# length here (in millisconds)

#PPS length = 1

# PPS cable delay can be set from -100 000 ns to 100 000 ns, default is 0 ns

#PPS cable delay = -1000

# The elevation mask can be set from 0 to 90 degrees, default is 5 degrees

#elevation mask = 10

# The user can specify which satellite systems must be used.
# The default is to use all.
# Use GLONASS only with care - it requires leap seconds to be known.
# Currently the software sets the leap second value to 18 s.

#satellite systems = GPS, GLONASS, GALILEO, QZSS

# The current leap second offset, required if only GLONASS is tracked.
# Note that this is a possible point of failure even though it is very 
# unlikely that a user will want to only track GLONASS...
#leap seconds = 18

# Note that the GCLK is not made available to the user on our Time Transfer System,
# but it is possible that a user builds their own board, so the option is here.
# The GCLK frequency output is not coherent with the VCLK PPS output and can
# have significant jitter. See manuals for details.
# GCLK output is set to Off by default. You can change that here:
# 0 == Off, 1 == On.

#GCLK on = 1

# GCLK output frequency range is 10 Hz to 40 MHz. Default is 10 MHz.

#GCLK freq = 5E6

# Fix antenna position. Note all three parameters must be valid.
# If this is not provided, or the values are invalid, the GPSDO
# will be set to Site Survey mode.
# Latitude is from -90 to 90 degrees, value is fractional degrees
# Longitude is from -180 to 180 degrees, value is fractional degrees
# Altitude if from -1000 to 18000 meters

#[antenna position]

#latitude = {latitude}
#longitude = {longitude}
#altitude = {altitude}
