# The diskreport script requires root access to work. The default user for
# the script is cvgps, so this sample configuration is written for that user.
# The script is capable of running continuously but the best way to use it is
# to install it as a cron snippet in /etc/cron.d/ and set it to run on a 
# schedule (I typically use 15 minutes). The cron snippet I use, saved to 
# /etc/cron.d/diskreport is:
# 0-59/15 * * * * root /home/cvgps/bin/diskreport.py -c /home/cvgps/etc/diskreport.conf

[disk]
device = /dev/nvme0

[path]
# Paths must be specified completely as the script is run as root.
data = /home/cvgps/raw/nvme0
file extension = dat
lock file = /home/cvgps/var/diskreport.lock

[user]
# The data file owner is changed to this user.
name = cvgps

[check]
# Default is to run the script only once then exit. If this is set to 
# False the script will run continuously (use kickstart to check) and
# the check interval is 60 minutes or as set below.
runonce = True
# Optional - specify checking interval in minutes, default is every hour
# This is only used if runonce = False above.
interval = 15
