# For Furuno GF-8805 

[main]
lock file = lockStatusCheck/furuno.lock

# The serial number is not software accessible. You have to place it in the 
# configuration if you want to access it from the system.
# The number can be found on the top of the GPSDO oscillator.

serial number = {Serial Number}

[comms]
port = /dev/furuno

# optional timeout (in seconds)
# Default is 10 seconds.

timeout = 30

[data]
path = raw/furuno
ext = gpsdo

[status]
path = lockStatusCheck
file name = furuno.status

# The following configuration options are optional
[receiver]
# This option can turn the antenna open warning on/off. This is useful when
# the antenna input is connected to a splitter without an impedance to simulate
# the presence of an antenna. Default is On.
# 0 == Off, 1 == On.

antenna open warning = 0

# The default PPS pulse length is 500 ms. You can state the required pusle
# length here (in millisconds)

PPS length = 1

# The GCLK frequency output is not coherent with the VCLK PPS output and can
# have significant jitter. See manuals for details.
# GCLK output is set to Off by default. You can change that here:
# 0 == Off, 1 == On.

#GCLK on = 1

# GCLK output frequency range is 10 Hz to 40 MHz. Default is 10 MHz.

#GCLK freq = 5E6
