# For Furuno GF-8805 s/n 24479689
[main]
lock file = lockStatusCheck/furuno.lock

[comms]
port = /dev/furuno
# optional (timeout in seconds)
# increased timeout to > 1 hour for restart tests.
timeout = 3605.0

[data]
path = raw/furuno
ext = gpsdo

[status]
path = lockStatusCheck
file name = furuno.status
